---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inferenceservice-user
  namespace: demo
  labels:
    app: anythingllm
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anythingllm-inferenceservice-access
  namespace: demo
  labels:
    app: anythingllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inferenceservice-user
subjects:
  - kind: ServiceAccount
    name: anythingllm
    namespace: {{ .Values.namespace }}
