apiVersion: v1
kind: Service
metadata:
  name: anythingllm-oauth-proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: anythingllm
  annotations:
    argocd.argoproj.io/sync-wave: "41"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth-proxy
  selector:
    app: anythingllm
