apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anythingllm
  namespace: {{ .Values.namespace }}
  labels:
    app: anythingllm
  annotations:
    argocd.argoproj.io/sync-wave: "42"
spec:
  to:
    kind: Service
    name: anythingllm-oauth-proxy
  port:
    targetPort: oauth-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
