apiVersion: v1
kind: Service
metadata:
  name: anythingllm
  namespace: {{ .Values.namespace }}
  labels:
    app: anythingllm
  annotations:
    argocd.argoproj.io/sync-wave: "41"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: anythingllm
