apiVersion: v1
kind: ServiceAccount
metadata:
  name: anythingllm
  namespace: {{ .Values.namespace }}
  labels:
    app: anythingllm
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    serviceaccounts.openshift.io/oauth-redirectreference.anythingllm: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"anythingllm"}}'